# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - id: "concord"
    main: ./cmd/concord
    binary: concord
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
      - -X github.com/palomachain/concord/config.version={{ .Tag }}
      - -X github.com/palomachain/concord/config.commit={{ .FullCommit }}
    goos:
      - linux
    goarch:
      - amd64
  - id: "whisper"
    main: ./cmd/whisper
    binary: whisper
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
      - -X github.com/palomachain/concord/config.version={{ .Tag }}
      - -X github.com/palomachain/concord/config.commit={{ .FullCommit }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - builds:
    - concord
    name_template: >-
      concord_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
  - builds:
    - whisper
    name_template: >-
      whisper_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^third_party_proto:'
      - '^scripts:'
      - '^docs:'
