# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - main: ./cmd/concord
    binary: concord
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
      - -x github.com/palomachain/concord/app.version={{ .tag }}
      - -x github.com/palomachain/concord/app.commit={{ .fullcommit }}
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/whisper
    binary: whisper
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
      - -x github.com/palomachain/whisper/app.version={{ .tag }}
      - -x github.com/palomachain/whisper/app.commit={{ .fullcommit }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^third_party_proto:'
      - '^scripts:'
      - '^docs:'
